version: "3"
services:
  nginx:
    ports:
      - "8800:80"
  node-app:
    build:
     context: .
     args: 
      NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules  
    environment:
      - NODE_ENV=development
      - MONGO_USER=azunda
      - MONGO_PASSWORD=dondizzy12
      - SESSION_SECRET=dondizzy121
    command: npm run dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=azunda
      - MONGO_INITDB_ROOT_PASSWORD=dondizzy12    
      