version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8800:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro  
  node-app:
    build: .
    # ports:
      # - "3000:3000" 
    environment:
      - PORT=8800
    depends_on:
      - mongo  

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=azunda
      - MONGO_INITDB_ROOT_PASSWORD=dondizzy12
    volumes:
      - mongo-db:/data/db  
  


volumes:
  mongo-db: